language: go
go:
  - 1.12.x
git:
  # Needs to include the commit of the latest tag
  depth: 50
  submodules: false
script:
  - export GO111MODULE=on
  - make
notifications:
  email:
      - oubiwann@gmail.com
